### PR TITLE
feat: add Ebola Zaire and rename config to snake_case for conformity

### PR DESCRIPTION
**Pull request by Taepper**
Added the first dataset from loculus data with all EbolaZaire. Only one dummy request is currently added

### CODE REVIEW

**Comment by corneliusroemer** [comment]
What do you mean by dummy request?

There's no ebola from Switzerland. So is the input data not real?

Or are you testing that the test can fail to test the test?

**Comment by Taepper** [comment]
Ehm, at least there is one in the input data

Also on Pathoplexus
https://pathoplexus.org/ebola-zaire/search?visibility_hostOriginCountry=true&geoLocCountry=Switzerland

And NCBI 
image

**Comment by Taepper** [comment]
By dummy I just mean that this one requests that is added here does not test for a lot of data integrity. This was more for testing the whole dataset in github actions

**Comment by corneliusroemer** [comment]
Oh wow, ok! I didn't know there was Ebola collected in Switzerland!

**Review by corneliusroemer — APPROVED** [review]

**Pull request merged**
